### ISSUE TITLE
Multiple option seems not working

### ISSUE THREAD

**Issue by delafred** [trentrichardson/UberUploadCropper#1]
Great job but multiple option seems not working 

When I put the line

'multiple'  : false,

It seem possible to add more images.

Thx 

Fred

**Comment by rnicholus** [comment]
The `multiple` option does not pertain to the total number of files you may upload.  Rather, if this option is set to `false`, you will not be able to select multiple files _at one time_.  See the [Fine Uploader documentation](https://github.com/valums/file-uploader/blob/master/readme.md) for more details.

**Comment by trentrichardson** [comment]
Multiple option should now work.  I am closing this issue.  Please re-open if this issue persists.
